export enum Role {
  CLIENTE = 'CLIENTE',
  CAJERO = 'CAJERO',
  DUENO = 'DUENO',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum TableStatus {
  LIBRE = 'LIBRE',
  OCUPADA = 'OCUPADA',
  RESERVADA = 'RESERVADA',
  FUERA_DE_SERVICIO = 'FUERA_DE_SERVICIO',
}

export enum ReservationStatus {
  PENDIENTE_PAGO = 'PENDIENTE_PAGO',
  EN_REVISION = 'EN_REVISION',
  CONFIRMADA = 'CONFIRMADA',
  ACTIVA = 'ACTIVA',
  CANCELADA = 'CANCELADA',
  COMPLETADA = 'COMPLETADA',
}

export enum PaymentStatus {
  PENDIENTE = 'PENDIENTE',
  VERIFICADO = 'VERIFICADO',
  RECHAZADO = 'RECHAZADO',
  REEMBOLSADO = 'REEMBOLSADO',
  CONVERTIDO_A_CREDITO = 'CONVERTIDO_A_CREDITO',
}

export enum PaymentMethodType {
  QR_BANCARIO = 'QR_BANCARIO',
  TIGO_MONEY = 'TIGO_MONEY',
  BILLETERA = 'BILLETERA',
  OTRO = 'OTRO',
}
